setwd("~/Desktop/Programming/MITx 15.071x/Week2")
Sys.setlocale("LC_ALL", "C")
climate = read.csv("climate_change.csv")
trainset = subset(climate, Year <= 2006)
testset = subset(climate, Year > 2006)
TempReg = lm(Temp ~ MEI + CO2 + CH4 + N2O + CFC.11 + CFC.12 + TSI + Aerosols, data = trainset)
TempReg1 = lm(Temp ~ MEI + TSI + Aerosols + N2O, data = trainset)
stepTemp = step(TempReg)
TempPrediction = predict(stepTemp, newdata = testset)
SSE = sum((TempPrediction - testset$Temp)^2)
SST = sum((testset$Temp - mean(trainset$Temp))^2)